image: 696577169457.dkr.ecr.eu-central-1.amazonaws.com/baseimages/python:3.7

stages:
- release

.release: &release
  stage: release
  script:
  - pip3 install -U twine
  - python3 setup.py bdist_wheel
  - twine upload --repository-url https://nexus.ccl/nexus/repository/$NEXUS_REPOSITORY_NAME/ dist/*

release-prod:
  extends: .release
  variables:
    NEXUS_REPOSITORY_NAME: 'pypi-hosted'
  only:
  - tags

release-snapshot:
  extends: .release
  variables:
    NEXUS_REPOSITORY_NAME: 'pypi-hosted-snapshots'
  when: manual
